services:
  kminder:
    build: ./app
    # ports:
    #   - 8001:8001
    volumes:
      - ./services.yaml:/app/services.yaml
      - ./services_history.yaml:/app/services_history.yaml
    environment:
      TZ: Asia/Yekaterinburg
      STARLINE_SLID_TOKEN: $STARLINE_SLID_TOKEN

  nginx:
    image: nginx:1.29.0-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - kminder
